/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables;


import java.util.function.Function;

import jooq.deliveryservice.database.Delivery;
import jooq.deliveryservice.database.Keys;
import jooq.deliveryservice.database.tables.records.DistrictRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class District extends TableImpl<DistrictRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>delivery.district</code>
     */
    public static final District DISTRICT = new District();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DistrictRecord> getRecordType() {
        return DistrictRecord.class;
    }

    /**
     * The column <code>delivery.district.id</code>.
     */
    public final TableField<DistrictRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>delivery.district.name</code>.
     */
    public final TableField<DistrictRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    private District(Name alias, Table<DistrictRecord> aliased) {
        this(alias, aliased, null);
    }

    private District(Name alias, Table<DistrictRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>delivery.district</code> table reference
     */
    public District(String alias) {
        this(DSL.name(alias), DISTRICT);
    }

    /**
     * Create an aliased <code>delivery.district</code> table reference
     */
    public District(Name alias) {
        this(alias, DISTRICT);
    }

    /**
     * Create a <code>delivery.district</code> table reference
     */
    public District() {
        this(DSL.name("district"), null);
    }

    public <O extends Record> District(Table<O> child, ForeignKey<O, DistrictRecord> key) {
        super(child, key, DISTRICT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Delivery.DELIVERY;
    }

    @Override
    public Identity<DistrictRecord, Integer> getIdentity() {
        return (Identity<DistrictRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DistrictRecord> getPrimaryKey() {
        return Keys.DISTRICT_PKEY;
    }

    @Override
    public District as(String alias) {
        return new District(DSL.name(alias), this);
    }

    @Override
    public District as(Name alias) {
        return new District(alias, this);
    }

    @Override
    public District as(Table<?> alias) {
        return new District(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public District rename(String name) {
        return new District(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public District rename(Name name) {
        return new District(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public District rename(Table<?> name) {
        return new District(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
