/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database;


import jooq.deliveryservice.database.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in delivery.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index INDEX_EMAIL = Internal.createIndex(DSL.name("index_email"), User.USER, new OrderField[] { User.USER.EMAIL }, true);
    public static final Index INDEX_USERNAME = Internal.createIndex(DSL.name("index_username"), User.USER, new OrderField[] { User.USER.USERNAME }, true);
}
