/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables.daos;


import java.util.List;
import java.util.Optional;

import jooq.deliveryservice.database.tables.District;
import jooq.deliveryservice.database.tables.records.DistrictRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistrictDao extends DAOImpl<DistrictRecord, jooq.deliveryservice.database.tables.pojos.District, Integer> {

    /**
     * Create a new DistrictDao without any configuration
     */
    public DistrictDao() {
        super(District.DISTRICT, jooq.deliveryservice.database.tables.pojos.District.class);
    }

    /**
     * Create a new DistrictDao with an attached configuration
     */
    public DistrictDao(Configuration configuration) {
        super(District.DISTRICT, jooq.deliveryservice.database.tables.pojos.District.class, configuration);
    }

    @Override
    public Integer getId(jooq.deliveryservice.database.tables.pojos.District object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.deliveryservice.database.tables.pojos.District> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(District.DISTRICT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.deliveryservice.database.tables.pojos.District> fetchById(Integer... values) {
        return fetch(District.DISTRICT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.deliveryservice.database.tables.pojos.District fetchOneById(Integer value) {
        return fetchOne(District.DISTRICT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<jooq.deliveryservice.database.tables.pojos.District> fetchOptionalById(Integer value) {
        return fetchOptional(District.DISTRICT.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.deliveryservice.database.tables.pojos.District> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(District.DISTRICT.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<jooq.deliveryservice.database.tables.pojos.District> fetchByName(String... values) {
        return fetch(District.DISTRICT.NAME, values);
    }
}
