/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables.records;


import jooq.deliveryservice.database.tables.CompanyCategory;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyCategoryRecord extends TableRecordImpl<CompanyCategoryRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>delivery.company_category.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>delivery.company_category.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>delivery.company_category.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>delivery.company_category.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CompanyCategory.COMPANY_CATEGORY.COMPANY_ID;
    }

    @Override
    public Field<Integer> field2() {
        return CompanyCategory.COMPANY_CATEGORY.CATEGORY_ID;
    }

    @Override
    public Integer component1() {
        return getCompanyId();
    }

    @Override
    public Integer component2() {
        return getCategoryId();
    }

    @Override
    public Integer value1() {
        return getCompanyId();
    }

    @Override
    public Integer value2() {
        return getCategoryId();
    }

    @Override
    public CompanyCategoryRecord value1(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public CompanyCategoryRecord value2(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public CompanyCategoryRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyCategoryRecord
     */
    public CompanyCategoryRecord() {
        super(CompanyCategory.COMPANY_CATEGORY);
    }

    /**
     * Create a detached, initialised CompanyCategoryRecord
     */
    public CompanyCategoryRecord(Integer companyId, Integer categoryId) {
        super(CompanyCategory.COMPANY_CATEGORY);

        setCompanyId(companyId);
        setCategoryId(categoryId);
    }

    /**
     * Create a detached, initialised CompanyCategoryRecord
     */
    public CompanyCategoryRecord(jooq.deliveryservice.database.tables.pojos.CompanyCategory value) {
        super(CompanyCategory.COMPANY_CATEGORY);

        if (value != null) {
            setCompanyId(value.getCompanyId());
            setCategoryId(value.getCategoryId());
        }
    }
}
