/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables.records;


import jooq.deliveryservice.database.tables.District;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistrictRecord extends UpdatableRecordImpl<DistrictRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>delivery.district.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>delivery.district.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>delivery.district.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>delivery.district.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return District.DISTRICT.ID;
    }

    @Override
    public Field<String> field2() {
        return District.DISTRICT.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public DistrictRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DistrictRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DistrictRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DistrictRecord
     */
    public DistrictRecord() {
        super(District.DISTRICT);
    }

    /**
     * Create a detached, initialised DistrictRecord
     */
    public DistrictRecord(Integer id, String name) {
        super(District.DISTRICT);

        setId(id);
        setName(name);
    }

    /**
     * Create a detached, initialised DistrictRecord
     */
    public DistrictRecord(jooq.deliveryservice.database.tables.pojos.District value) {
        super(District.DISTRICT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
        }
    }
}
