/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables.records;


import jooq.deliveryservice.database.tables.Subcategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubcategoryRecord extends UpdatableRecordImpl<SubcategoryRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>delivery.subcategory.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>delivery.subcategory.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>delivery.subcategory.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>delivery.subcategory.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>delivery.subcategory.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>delivery.subcategory.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Subcategory.SUBCATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return Subcategory.SUBCATEGORY.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Subcategory.SUBCATEGORY.CATEGORY_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCategoryId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCategoryId();
    }

    @Override
    public SubcategoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SubcategoryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SubcategoryRecord value3(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public SubcategoryRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubcategoryRecord
     */
    public SubcategoryRecord() {
        super(Subcategory.SUBCATEGORY);
    }

    /**
     * Create a detached, initialised SubcategoryRecord
     */
    public SubcategoryRecord(Integer id, String name, Integer categoryId) {
        super(Subcategory.SUBCATEGORY);

        setId(id);
        setName(name);
        setCategoryId(categoryId);
    }

    /**
     * Create a detached, initialised SubcategoryRecord
     */
    public SubcategoryRecord(jooq.deliveryservice.database.tables.pojos.Subcategory value) {
        super(Subcategory.SUBCATEGORY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCategoryId(value.getCategoryId());
        }
    }
}
