/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables.records;


import jooq.deliveryservice.database.tables.UserInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>delivery.user_info.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>delivery.user_info.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserInfo.USER_INFO.USER_ID;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public UserInfoRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserInfoRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(Integer userId) {
        super(UserInfo.USER_INFO);

        setUserId(userId);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(jooq.deliveryservice.database.tables.pojos.UserInfo value) {
        super(UserInfo.USER_INFO);

        if (value != null) {
            setUserId(value.getUserId());
        }
    }
}
