/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer userInfoId;
    private Integer districtId;
    private String street;
    private String house;
    private String flat;

    public Address() {}

    public Address(Address value) {
        this.id = value.id;
        this.userInfoId = value.userInfoId;
        this.districtId = value.districtId;
        this.street = value.street;
        this.house = value.house;
        this.flat = value.flat;
    }

    public Address(
        Integer id,
        Integer userInfoId,
        Integer districtId,
        String street,
        String house,
        String flat
    ) {
        this.id = id;
        this.userInfoId = userInfoId;
        this.districtId = districtId;
        this.street = street;
        this.house = house;
        this.flat = flat;
    }

    /**
     * Getter for <code>delivery.address.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>delivery.address.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>delivery.address.user_info_id</code>.
     */
    public Integer getUserInfoId() {
        return this.userInfoId;
    }

    /**
     * Setter for <code>delivery.address.user_info_id</code>.
     */
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * Getter for <code>delivery.address.district_id</code>.
     */
    public Integer getDistrictId() {
        return this.districtId;
    }

    /**
     * Setter for <code>delivery.address.district_id</code>.
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * Getter for <code>delivery.address.street</code>.
     */
    public String getStreet() {
        return this.street;
    }

    /**
     * Setter for <code>delivery.address.street</code>.
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for <code>delivery.address.house</code>.
     */
    public String getHouse() {
        return this.house;
    }

    /**
     * Setter for <code>delivery.address.house</code>.
     */
    public void setHouse(String house) {
        this.house = house;
    }

    /**
     * Getter for <code>delivery.address.flat</code>.
     */
    public String getFlat() {
        return this.flat;
    }

    /**
     * Setter for <code>delivery.address.flat</code>.
     */
    public void setFlat(String flat) {
        this.flat = flat;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Address other = (Address) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userInfoId == null) {
            if (other.userInfoId != null)
                return false;
        }
        else if (!this.userInfoId.equals(other.userInfoId))
            return false;
        if (this.districtId == null) {
            if (other.districtId != null)
                return false;
        }
        else if (!this.districtId.equals(other.districtId))
            return false;
        if (this.street == null) {
            if (other.street != null)
                return false;
        }
        else if (!this.street.equals(other.street))
            return false;
        if (this.house == null) {
            if (other.house != null)
                return false;
        }
        else if (!this.house.equals(other.house))
            return false;
        if (this.flat == null) {
            if (other.flat != null)
                return false;
        }
        else if (!this.flat.equals(other.flat))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userInfoId == null) ? 0 : this.userInfoId.hashCode());
        result = prime * result + ((this.districtId == null) ? 0 : this.districtId.hashCode());
        result = prime * result + ((this.street == null) ? 0 : this.street.hashCode());
        result = prime * result + ((this.house == null) ? 0 : this.house.hashCode());
        result = prime * result + ((this.flat == null) ? 0 : this.flat.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(userInfoId);
        sb.append(", ").append(districtId);
        sb.append(", ").append(street);
        sb.append(", ").append(house);
        sb.append(", ").append(flat);

        sb.append(")");
        return sb.toString();
    }
}
