/*
 * This file is generated by jOOQ.
 */
package jooq.deliveryservice.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer companyId;
    private Integer categoryId;

    public CompanyCategory() {}

    public CompanyCategory(CompanyCategory value) {
        this.companyId = value.companyId;
        this.categoryId = value.categoryId;
    }

    public CompanyCategory(
        Integer companyId,
        Integer categoryId
    ) {
        this.companyId = companyId;
        this.categoryId = categoryId;
    }

    /**
     * Getter for <code>delivery.company_category.company_id</code>.
     */
    public Integer getCompanyId() {
        return this.companyId;
    }

    /**
     * Setter for <code>delivery.company_category.company_id</code>.
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for <code>delivery.company_category.category_id</code>.
     */
    public Integer getCategoryId() {
        return this.categoryId;
    }

    /**
     * Setter for <code>delivery.company_category.category_id</code>.
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CompanyCategory other = (CompanyCategory) obj;
        if (this.companyId == null) {
            if (other.companyId != null)
                return false;
        }
        else if (!this.companyId.equals(other.companyId))
            return false;
        if (this.categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!this.categoryId.equals(other.categoryId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.companyId == null) ? 0 : this.companyId.hashCode());
        result = prime * result + ((this.categoryId == null) ? 0 : this.categoryId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CompanyCategory (");

        sb.append(companyId);
        sb.append(", ").append(categoryId);

        sb.append(")");
        return sb.toString();
    }
}
